=== atlanticwave-sdx/sense-sdx/schemas/sense-schema-intent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "service_instance_uuid": {
      "type": "string",
      "minLength": 1
    },
    "data": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1
        },
        "connections": {
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "required": [
              "name"
            ],
            "properties": {
              "bandwidth": {
                "type": "object",
                "properties": {
                  "qos_class": {
                    "type": "string",
                    "minLength": 1
                  },
                  "capacity": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "qos_class",
                  "capacity"
                ]
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "terminals": {
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                  "required": [
                    "vlan_tag",
                    "uri"
                  ],
                  "properties": {
                    "vlan_tag": {
                      "type": "string",
                      "minLength": 1
                    },
                    "uri": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              }
            }
          }
        }
      },
      "required": [
        "type",
        "connections"
      ]
    },
    "service": {
      "type": "string",
      "minLength": 1
    },
    "options": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "service_profile_uuid": {
      "type": "string",
      "minLength": 1
    },
    "queries": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    }
  },
  "required": [
    "service_instance_uuid",
    "data",
    "service",
    "options",
    "service_profile_uuid",
    "queries"
  ]
}

=== atlanticwave-sdx/sense-sdx/tests/data/intent.json
{
    "service_instance_uuid": "556c262e-1f6c-44cf-911c-f772d7c343fa",
    "data": {
        "type": "Multi-Path P2P VLAN",
        "connections": [
            {
                "bandwidth": {
                    "qos_class": "guaranteedCapped",
                    "capacity": "100"
                },
                "name": "Connection 1",
                "terminals": [
                    {
                        "vlan_tag": "any",
                        "uri": "urn:ogf:network:icair.org:2013:mren8700:p4test"
                    },
                    {
                        "vlan_tag": "any",
                        "uri": "urn:ogf:network:ampath.net:2013:topology:rare-mia0001"
                    }
                ]
            }
        ]
    },
    "service": "dnc",
    "options": [],
    "service_profile_uuid": "d2dc8b4f-7445-4d9e-ac56-2ff82203685c",
    "queries": []
}
